### ISSUE TITLE
[4pt] Add method to replace and delete exists frontend module

### ISSUE THREAD

**Issue by rgbabaev** [tarantool/frontend-core#122]
Proposals:

1. Add `replace` method that doesn't check for module existence.

1. Add third bool argument 'replace' to `add` method.

**Comment by no1seman** [comment]
Seems that need also not to replace or delete lua-methods but also trigger WebUI to reload, because if we removing some forntend module in runtime, for example if it's used by some Cartridge Role and it was disabled
