### ISSUE TITLE
Update vulnerabile react-dev-utils 9.0.1 to latest 11.0.4

### ISSUE THREAD

**Issue by no1seman** [tarantool/frontend-core#123]
immer  <8.0.1
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1603
No fix available
node_modules/immer
  react-dev-utils  6.0.6-next.9b4009d7 - 11.0.2
  Depends on vulnerable versions of immer
  node_modules/@tarantool.io/frontend-core/node_modules/react-dev-utils
  node_modules/react-dev-utils
    @tarantool.io/frontend-core  *
    Depends on vulnerable versions of react-dev-utils
    node_modules/@tarantool.io/frontend-core

**Comment by rgbabaev** [comment]
Closed in #132.
