### ISSUE TITLE
Side menu broken on Mac OS Safari 

### ISSUE THREAD

**Issue by KlonD90** [tarantool/frontend-core#24]
Not fully visible

**Comment by KlonD90** [comment]
![image](https://user-images.githubusercontent.com/790299/66560772-bb1ae300-eb60-11e9-8077-0cb3063bbb1d.png)

**Comment by iv-ov** [comment]
I found a way to fix this that involves using the CSS property "flex-grow".

Browser support for `flex-grow`
**Usage relative:**
<img width="1483" alt="изображение" src="https://user-images.githubusercontent.com/7147989/69181764-bf073100-0b20-11ea-890f-0669d24d1816.png">
**By versions:**
<img width="1482" alt="изображение" src="https://user-images.githubusercontent.com/7147989/69182155-8025ab00-0b21-11ea-8907-a77f06b713b6.png">

I hope it's Ok for us

**Comment by iv-ov** [comment]
`height: '40px'` — 40px is the height of one menu item. The scrollable area will not shrink below this value (but this is a completely extreme case)

**Comment by artur-barsegyan** [comment]
Maybe, we need a tool for this issue for cross-browser test.

**Comment by iv-ov** [comment]
I think we can
• manually test this fix https://github.com/tarantool/frontend-core/pull/36 and merge it to do good to our current Safari users
• leave this issue open while we decide about testing
