### ISSUE TITLE
[1pt] [UI] Code: Change  tooltip for FileTreeElement__btns

### ISSUE THREAD

**Issue by Errora** [tarantool/frontend-core#42]
**Шаги:**

1. Перейти на страницу Code 
2. Добавить файл/папку
3. Навести курсором на одну из кнопок на панели кнопок

**Ожидаемый результат:**

Во всплывающей подсказке отображается название кнопки

**Полученный результат:**

Во всплывающей подсказке отображается название файла/папки: 
http://joxi.ru/52a1jDBtEdLle2

**Comment by rgbabaev** [comment]
It was fixed earlier
