### ISSUE TITLE
[UI] Code: Empty file after editing and deleting

### ISSUE THREAD

**Issue by Errora** [tarantool/frontend-core#49]
**Шаги:**
1. Перейти на страницу Code,
2. Создать файл,
3. Нажать кнопку Apply,
4. Кликнуть по созданному файлу (для того чтоб открыть редактор кода),
5. Удалить файл,
6. Внести изменения в редактор,
7. Нажать кнопку Apply

**Ожидаемый результат:**
Система на 6 шаге не даст внести изменения в редактор, так как файл был удален

**Полученный результат:**
Система выдает сообщение, что все сохранено, но содержимое файла пропадает и файл пустой висит в дереве

**Comment by usenko-timur** [comment]
@OlgaYakovleva 
Похоже что проблема уже исправлена, нужно перепроверить и закрыть.
