### ISSUE TITLE
[2pt] [UI] Configuration files: remove redirect when trying download configuration without bootstrap

### ISSUE THREAD

**Issue by Errora** [tarantool/frontend-core#50]
**Предусловие:**
Бутстрап не выполнен

**Шаги:**
1. Перейти в Configuration files
2. Нажать кнопку Download 

**Ожидаемый результат:**
Система выдает ошибку о том, что бутстрап не выполнен

**Полученный результат:**
Происходит редирект на страницу с ошибкой:
http://joxi.ru/Q2KnKo1ILRQgqm

**Comment by usenko-timur** [comment]
Эта проблема уровня cartridge.
PR: https://github.com/tarantool/cartridge/pull/1707

**Comment by OlgaYakovleva** [comment]
Scenario on TDG2:
1. Clear dev\output 
2. Start tdg2 (not bootstraped)
3. Open page "Configuration files"
There is error message: "No remotes with role 'core' avaliable"

Scenario on Cartridge:
1. Clear cartridge\tmp
2. Start cartridge (not bootstraped)
3. Open page "Configuration files"

There icon with message: "Cluster isn't bootstrapted yet"
