### ISSUE TITLE
Refactor filters API and method

### ISSUE THREAD

**Issue by KlonD90** [tarantool/frontend-core#64]
Now filters is a part of registration module but it have next problems:
1. `registerModule` - too complicated method
2. It depends on first point. It's single mounted point. If you need add filter you must register module
3. We don't have convenient method to update filter only. Or remove filters.

So my proposal:
Add disposable (return dispose function) method `registerPageFilter` with next api `registerPageFilter(filter)`. 

Add redux event `APPLY_FILTERS` that will be affect menu state.

With next dispatchable events: 
`core:pageFilter:apply`
`core:pageFilter:applied`

On applied we could update black list and other things.

Usage example:

```
const unsubscribeFilter = core.registerPageFilter(m => m.includes('admin'))
// dispatch events
unsubscribeFilter()
// dispatch another events

```

Add method to menu reducer `isBlacklistedPath`

**Comment by KlonD90** [comment]
Previous style of work should be enabled but will be marked as deprecated

**Comment by aShelist** [comment]
It sounds good

**Comment by KlonD90** [comment]
thanks
