### ISSUE TITLE
Proposal: Add passing params from Lua to JS

### ISSUE THREAD

**Issue by KlonD90** [tarantool/frontend-core#65]
If we need parameters from backend that's we should use in frontend. Like a we want to set up a key in Lua. Or some other like redirect endpoint without usage an API.

Example:

**Lua:**
```
front.set_variable('name', 'value')
```

It will be translated to the top of `<head>`

**JS:**
```
window.__TNT_PASSED_VARIABLES__.name = JSON.parse('"value"');
```

Lua 'value' will be transform by `json.encode`

**Comment by rosik** [comment]
I like the proposal, but why json? What values are you going to pass that way? Could you provide an example of such variable. `demo_uri`, what else?

**Comment by KlonD90** [comment]
@rosik it could be something like a store configuration that will be applied on frontend part. Example: default Code editor settings: {smarttabs: true, padding: 2}

**Comment by rosik** [comment]
Ok, let it be json.
